<?php

/**
 * @file
 * module for adding a link to a block title tooltip.
 */

// Variable Table Prefex
define('BLOCK_TITLE_TOOLTOP_VARIABLE_PREFIX', 'block_title_tooltip_');

/**
 * Implements hook_form_alter().
 */
function block_title_tooltip_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'block_admin_configure' || $form_id == 'block_add_block_form') {
    $block = new stdClass();
    $block->module = $form['module']['#value'];
    $block->delta = $form['delta']['#value'];
    $title_tooltip_data = block_title_tooltip_get_data($block);
    //Define TitleTooltip form elements
    $form['settings']['block_title_tooltip'] = array(
      '#type' => 'fieldset',
      '#title' => t('Block Title Tooltip Settings'),
      '#collapsible' => TRUE,
      '#weight' => 0,
      '#tree' => TRUE,
    );
    $form['settings']['block_title_tooltip']['title_tooltip'] = array(
      '#type' => 'textfield',
      '#title' => t('Title Tooltip'),
      '#default_value' => $title_tooltip_data,
      '#description' => t('Block Titletooltip.'),
    );
    if (!isset($form['block_settings']['#weight'])) {
      $form['block_settings']['#weight'] = -1;
    }
    $form['#submit'][] = 'block_title_tooltip_form_submit';
  }
}

/**
 * Implements hook_init().
 * Adds the tooltips stylesheet to the page.
 */
function block_title_tooltip_init() {
  if (function_exists('drupal_add_css')) // If not caching
    drupal_add_css(drupal_get_path('module', 'block_title_tooltip') . '/block_title_tooltip.css', 'module', 'all', TRUE);
}


/**
 * Implements hook_submit().
 */
function block_title_tooltip_form_submit($form, &$form_state) {
  $block = new stdClass();
  $block->module = $form['module']['#value'];
  $block->delta = $form_state['values']['delta'];
  $title_tooltip = $form_state['values']['block_title_tooltip']['title_tooltip'];
  $data = array(
    'title_tooltip' => $title_tooltip
  );
  if (empty($title_tooltip)) {
    block_title_tooltip_delete_data($block);
  }
  else {
    block_title_tooltip_save_data($block, $data);
  }
}

/**
 * Function to delete block data.
 * @param object - Block object
 */
function block_title_tooltip_delete_data($block) {
  if (!isset($block->module) && !isset($block->delta)) {
    return FALSE;
  }
  $varname = BLOCK_TITLE_TOOLTOP_VARIABLE_PREFIX . $block->module . '_' . $block->delta;
  variable_del($varname);
}

/**
 * Function to save Block title tooltip data
 * @param object - Block object
 * @param array - Array containing data
 * $data['title_tooltip'] - String to save
 */
function block_title_tooltip_save_data($block, $data) {
  if (empty($block->module) || empty($block->delta)) {
    return FALSE;
  }
  $varname = BLOCK_TITLE_TOOLTOP_VARIABLE_PREFIX . $block->module . '_' . $block->delta;
  variable_set($varname, $data);
}

/**
 * Implements hook_preprocess_block().
 */
function block_title_tooltip_preprocess_block(&$vars, $hook) {
  global $user;
  if ($hook == 'block') {
    $data = block_title_tooltip_get_data($vars['block']);
    if ($data) {
      $vars['block']->title_tooltip = (isset($data['title_tooltip'])) ? $data['title_tooltip'] : NULL;
      // PHP Eval
      if (module_exists('php')) {
        $vars['block']->title_tooltip = php_eval($vars['block']->title_tooltip);
      }
      $display = (isset($data['display'])) ? $data['display'] : TRUE;
      if (!empty($vars['block']->title_tooltip) && $display) {
        $attributes = array(
          'attributes' => array(
            'class' => array('block-title-link'),
          ),
          'html' => TRUE,
        );
        $arbitrary_array = array(
          'path' => drupal_get_path('module', 'block_title_tooltip') . '/image/callout.gif',
          'attributes' => array('class' => 'block_title_tooltip'),
        );
        $vars['block']->subject = '<div class="tooltip">' . t($vars['block']->subject) . '<span>' . theme_image($arbitrary_array) . t($vars['block']->title_tooltip) . '</span></div>';
      }
    }
  }
}

/**
 * Function to return the data associated with a block_title_tooltip
 * @param object $block - Block to search by
 * @return array containing display_link and title_tooltip variable.
 */
function block_title_tooltip_get_data($block) {
  if (!isset($block->module) && !isset($block->delta)) {
    return FALSE;
  }
  $varname = BLOCK_TITLE_TOOLTOP_VARIABLE_PREFIX . $block->module . '_' . $block->delta;
  $result = variable_get($varname, NULL);
  if (is_string($result)) {
    return array('title_tooltip' => $result, 'display' => TRUE);
  }
  elseif (is_array($result)) {
    return $result;
  }
  else {
    return FALSE;
  }
}
